language: en

pipeline:
- name: "SpacyNLP"
  case_sensitive: false
- name: "SpacyEntityExtractor"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: "http://localhost:8000"
  locale: "en_IN"
  timezone: "Asia/Kolkata"
  dimensions: ["time"]